import React, { useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, Camera, CheckCircle, Compass, LifeBuoy, MapPin, Navigation, Radio, Send, ShieldCheck, Smartphone } from 'lucide-react';
import { CitizenReport, GeoLocation, IncidentCategory, RegionProfile, RiskAnalysisResult, Shelter, SimulationState } from '../types';
import { assessLocationRisk, calculateResponsePriority } from '../utils/riskCalculators';
import { REGIONS } from '../data/disasterData';
import { SUNDARBANS_GRAPH } from '../priorityResponse/graphData';
import { evaluateIncident } from '../priorityResponse/responseEngine';
import { ResponseResult } from '../priorityResponse/types';

interface CitizenPortalProps { shelters: Shelter[]; simState: SimulationState; onSubmitReport: (newReport: CitizenReport) => void; onSelectShelterOnMap?: (shelter: Shelter) => void; currentRegion?: RegionProfile; routeResult?: ResponseResult; }
const AVERAGE_RESPONSE_SPEED_KMH = 35;
const formatEta = (distance: number | null) => { if (distance === null) return '—'; const minutes = Math.round((distance / AVERAGE_RESPONSE_SPEED_KMH) * 60); return minutes < 60 ? `${minutes} min` : `${Math.floor(minutes / 60)}h ${minutes % 60}m`; };

export const CitizenPortal: React.FC<CitizenPortalProps> = ({ shelters = [], simState, onSubmitReport, onSelectShelterOnMap, currentRegion = REGIONS[0], routeResult }) => {
  const locationNodes = useMemo(() => Object.values(SUNDARBANS_GRAPH.nodeMap).filter((node) => node.type === 'LOCATION').sort((a, b) => a.displayName.localeCompare(b.displayName)), []);
  const initialNode = SUNDARBANS_GRAPH.nodeMap['s-34'] || locationNodes[0];
  const locationFromNode = (nodeId: string): GeoLocation => { const node = SUNDARBANS_GRAPH.nodeMap[nodeId]; return { lat: node.lat, lng: node.lon, address: node.displayName, elevation: 4, slopeAngle: 1, distanceToRiver: 120 }; };
  const [selectedNodeId, setSelectedNodeId] = useState(initialNode.nodeId);
  const [locationMode, setLocationMode] = useState<'selected' | 'scanned'>('selected');
  const [currentLocation, setCurrentLocation] = useState<GeoLocation>(() => locationFromNode(initialNode.nodeId));
  const [locationAssessment, setLocationAssessment] = useState<RiskAnalysisResult>(() => assessLocationRisk(locationFromNode(initialNode.nodeId), simState, [], shelters));
  const [localRoute, setLocalRoute] = useState<ResponseResult>(() => evaluateIncident({ incidentId: 'citizen-location', priorityScore: 50, location: locationFromNode(initialNode.nodeId) }));
  const [isScanning, setIsScanning] = useState(false); const [scanNotice, setScanNotice] = useState<string | null>(null);
  const [description, setDescription] = useState(''); const [category, setCategory] = useState<IncidentCategory>('flash_flood');
  const [reporterName, setReporterName] = useState('Resident Citizen'); const [contactNumber, setContactNumber] = useState(currentRegion.state === 'West Bengal' ? '+91 98321-77810' : '');
  const [trappedCount, setTrappedCount] = useState(''); const [imagePreview, setImagePreview] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false); const [submittedSuccess, setSubmittedSuccess] = useState(false); const [sosActive, setSosActive] = useState(false); const [sosPersonsCount, setSosPersonsCount] = useState(2);
  const scanRequestRef = useRef(0);
  const reportSubmittingRef = useRef(false);
  const sosSubmittedRef = useRef(false);
  const applyLocation = (location: GeoLocation, mode: 'selected' | 'scanned', nodeId?: string) => { setCurrentLocation(location); setLocationMode(mode); if (nodeId) setSelectedNodeId(nodeId); setLocationAssessment(assessLocationRisk(location, simState, [], shelters)); setLocalRoute(evaluateIncident({ incidentId: 'citizen-location', priorityScore: 50, location })); };
  useEffect(() => { setLocationAssessment(assessLocationRisk(currentLocation, simState, [], shelters)); }, [currentLocation, simState, shelters]);
  useEffect(() => { if (routeResult && routeResult.originNodeId === localRoute.originNodeId) setLocalRoute(routeResult); }, [routeResult, localRoute.originNodeId]);
  const handleScanLocation = () => { const requestId = ++scanRequestRef.current; setIsScanning(true); const useLocation = (location: GeoLocation, notice?: string) => { if (requestId !== scanRequestRef.current) return; applyLocation(location, 'scanned'); setScanNotice(notice || 'Location scanned. Your route has been updated.'); setIsScanning(false); }; if (!('geolocation' in navigator)) { useLocation({ lat: 22.365, lng: 88.838, address: 'Approximate Sundarbans location', elevation: 4, slopeAngle: 1, distanceToRiver: 120 }, 'GPS is unavailable; using an approximate Sundarbans location.'); return; } navigator.geolocation.getCurrentPosition((position) => useLocation({ lat: position.coords.latitude, lng: position.coords.longitude, address: 'Your scanned GPS coordinates', elevation: 4, slopeAngle: 1, distanceToRiver: 120 }), () => useLocation({ lat: 22.365, lng: 88.838, address: 'Approximate Sundarbans location', elevation: 4, slopeAngle: 1, distanceToRiver: 120 }, 'Unable to access GPS; using an approximate Sundarbans location.')); };
  const handleImageUpload = (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onloadend = () => setImagePreview(reader.result as string); reader.readAsDataURL(file); };
  const submitReport = (event: React.FormEvent) => { event.preventDefault(); if (reportSubmittingRef.current || !description.trim()) return; reportSubmittingRef.current = true; setIsSubmitting(true); const peopleNeedingHelp = Number(trappedCount); const priority = calculateResponsePriority({ category, trappedCount: peopleNeedingHelp, waterDepthCm: 0, debrisHeightM: 0, severity: peopleNeedingHelp > 0 ? 'critical' : 'high' }); onSubmitReport({ id: `rep-${Date.now()}`, title: `${category.replace('_', ' ')} reported at ${currentLocation.address}`, category, description, location: currentLocation, reportedAt: 'Just now', reporterName, contactNumber, trappedCount: peopleNeedingHelp, imageUrl: imagePreview || undefined, severity: peopleNeedingHelp > 0 ? 'critical' : 'high', status: 'pending', priorityTier: priority.priorityTier, priorityScore: priority.priorityScore, aiVerification: { verified: true, confidence: 0.94, hazardKeywords: [category, 'citizen alert'], urgencyReasoning: priority.reasoning } }); setIsSubmitting(false); setSubmittedSuccess(true); setDescription(''); setImagePreview(null); };
  const handleTriggerSOS = () => { if (sosSubmittedRef.current) return; sosSubmittedRef.current = true; setSosActive(true); onSubmitReport({ id: `sos-${Date.now()}`, title: `An unreachable region has been reported (${currentLocation.address})`, category: 'trapped_civilians', description: 'Citizens demand an airlift rescue', location: currentLocation, reportedAt: 'Just now', reporterName: reporterName || 'Resident Citizen', contactNumber, trappedCount: sosPersonsCount, waterDepthCm: 120, severity: 'critical', status: 'pending', priorityTier: 'P1_CRITICAL', priorityScore: 100, aiVerification: { verified: true, confidence: 0.99, hazardKeywords: ['SOS', 'unreachable region', 'airlift rescue'], urgencyReasoning: 'Citizen SOS submitted through the existing incident pipeline.' } }); };
  const center = localRoute.selectedCenterId ? SUNDARBANS_GRAPH.nodeMap[localRoute.selectedCenterId] : null;
  const routeClass = localRoute.status === 'ROUTE_FOUND' ? 'border-emerald-700 bg-emerald-950/50 text-emerald-100' : localRoute.status === 'NO_FEASIBLE_ROUTE' ? 'border-red-700 bg-red-950/50 text-red-100' : 'border-amber-700 bg-amber-950/50 text-amber-100';
  return <div className="max-w-4xl mx-auto p-4 sm:p-6 space-y-5 text-slate-100">
    <section className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-xl space-y-4"><div className="flex items-start gap-3"><Smartphone className="w-6 h-6 text-cyan-400 mt-0.5" /><div><h1 className="font-bold text-lg text-white">Citizen Safety & Route Portal</h1><p className="text-xs text-slate-400">Find a feasible government rescue center, report hazards, or request emergency support.</p></div></div><div className="grid sm:grid-cols-[1fr_auto_1fr] gap-3 items-end"><label className="text-xs text-slate-300 font-semibold">Select Sundarbans location<select value={selectedNodeId} onChange={(e) => applyLocation(locationFromNode(e.target.value), 'selected', e.target.value)} className="mt-1.5 w-full bg-slate-950 border border-slate-700 rounded-lg p-2.5 text-white">{locationNodes.map((node) => <option key={node.nodeId} value={node.nodeId}>{node.displayName}</option>)}</select></label><span className="text-xs text-slate-500 text-center pb-2">OR</span><button onClick={handleScanLocation} disabled={isScanning} className="min-h-10 px-4 rounded-lg bg-cyan-600 hover:bg-cyan-500 disabled:opacity-60 text-sm font-bold flex items-center justify-center gap-2"><MapPin className="w-4 h-4" />{isScanning ? 'Scanning…' : 'Scan My Location'}</button></div>{scanNotice && <p className="text-xs text-cyan-200 bg-cyan-950/40 border border-cyan-900 rounded-lg p-2.5">{scanNotice}</p>}<div className="text-xs text-slate-400 flex items-center gap-2"><Navigation className="w-4 h-4 text-cyan-400" />{locationMode === 'scanned' ? 'Scanned location' : 'Selected location'}: <span className="text-slate-200 font-semibold">{currentLocation.address}</span></div></section>
    <section className={`rounded-2xl border p-5 space-y-3 ${routeClass}`}>{localRoute.status === 'ROUTE_FOUND' ? <><div className="flex gap-2 items-center"><CheckCircle className="w-5 h-5 text-emerald-400" /><h2 className="font-bold">Successful route found.</h2></div><div className="grid sm:grid-cols-3 gap-3 text-sm"><div><span className="block text-xs opacity-70">Government Center</span><strong>{center?.displayName || localRoute.selectedCenterId}</strong></div><div><span className="block text-xs opacity-70">Distance</span><strong>{localRoute.distance?.toFixed(1)} km</strong></div><div><span className="block text-xs opacity-70">Estimated Reach Time</span><strong>{formatEta(localRoute.distance)}</strong></div></div><div className="text-xs font-bold tracking-wide text-emerald-300">SAFE ROUTE AVAILABLE</div><p className="text-xs opacity-80">Route: {localRoute.path.map((nodeId) => SUNDARBANS_GRAPH.nodeMap[nodeId]?.displayName || nodeId).join(' → ')}</p></> : localRoute.status === 'NO_FEASIBLE_ROUTE' ? <><div className="flex gap-2 items-center"><AlertTriangle className="w-5 h-5 text-red-400" /><h2 className="font-bold">Sorry, there is no route available. Call for an emergency SOS.</h2></div><p className="text-xs opacity-80">Ground routing has failed. Submit SOS below to send an airlift request through the incident pipeline.</p></> : <div className="flex gap-2 items-center"><AlertTriangle className="w-5 h-5 text-amber-400" /><h2 className="font-bold">The route is blocked. We are trying to reroute to an alternative path...</h2></div>}</section>
    <section className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-4"><div className="flex gap-2 items-center"><ShieldCheck className="w-5 h-5 text-cyan-400" /><h2 className="font-bold">Location risk</h2><span className="ml-auto text-xs font-bold text-amber-300 uppercase">{locationAssessment.compositeRiskTier} risk</span></div><div className="grid sm:grid-cols-2 gap-3 text-sm"><div className="bg-slate-950 rounded-xl p-3">Flood risk <strong className="float-right text-cyan-300">{locationAssessment.floodRisk.score}%</strong></div><div className="bg-slate-950 rounded-xl p-3">Landslide risk <strong className="float-right text-amber-300">{locationAssessment.landslideRisk.score}%</strong></div></div>{locationAssessment.nearestShelter && <div className="text-xs bg-slate-950 rounded-xl p-3 flex flex-wrap gap-2 items-center"><span>Nearby shelter: <strong>{locationAssessment.nearestShelter.name}</strong></span>{onSelectShelterOnMap && <button onClick={() => onSelectShelterOnMap(locationAssessment.nearestShelter!)} className="ml-auto text-cyan-300 hover:text-cyan-200 flex gap-1 items-center"><Compass className="w-4 h-4" />View on map</button>}<a href={`tel:${locationAssessment.nearestShelter.contactNumber}`} className="text-emerald-300 flex gap-1 items-center"><LifeBuoy className="w-4 h-4" />Call shelter</a></div>}</section>
    <section className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-4"><div className="flex gap-2 items-center"><Camera className="w-5 h-5 text-amber-400" /><div><h2 className="font-bold">Report a hazard</h2><p className="text-xs text-slate-400">Your selected or scanned location is included with this report.</p></div></div>{submittedSuccess ? <div className="p-4 rounded-xl bg-emerald-950/40 border border-emerald-800 text-sm text-emerald-200 flex gap-2"><CheckCircle className="w-5 h-5" />Report submitted to the emergency incident pipeline.</div> : <form onSubmit={submitReport} className="space-y-3 text-xs"><label>Hazard type<select value={category} onChange={(e) => setCategory(e.target.value as IncidentCategory)} className="mt-1 w-full bg-slate-950 border border-slate-700 rounded-lg p-2.5 text-white">{['flash_flood', 'landslide', 'trapped_civilians', 'road_blocked', 'bridge_damaged', 'mudslide'].map((item) => <option key={item} value={item}>{item.replaceAll('_', ' ')}</option>)}</select></label><label>Description<textarea value={description} onChange={(e) => setDescription(e.target.value)} rows={3} className="mt-1 w-full bg-slate-950 border border-slate-700 rounded-lg p-2.5 text-white" placeholder="Describe the situation and people at risk." /></label><div className="grid sm:grid-cols-2 gap-3"><label>People needing help<input type="number" min="0" value={trappedCount} onChange={(e) => setTrappedCount(e.target.value)} className="mt-1 w-full bg-slate-950 border border-slate-700 rounded-lg p-2.5 text-white" /></label></div><div className="grid sm:grid-cols-2 gap-3"><label>Your name<input value={reporterName} onChange={(e) => setReporterName(e.target.value)} className="mt-1 w-full bg-slate-950 border border-slate-700 rounded-lg p-2.5 text-white" /></label><label>Contact number<input value={contactNumber} onChange={(e) => setContactNumber(e.target.value)} className="mt-1 w-full bg-slate-950 border border-slate-700 rounded-lg p-2.5 text-white" /></label></div><label className="inline-flex gap-2 items-center cursor-pointer text-slate-300"><Camera className="w-4 h-4 text-amber-400" />Attach photo<input type="file" accept="image/*" onChange={handleImageUpload} className="hidden" /></label>{imagePreview && <img src={imagePreview} alt="Hazard attachment preview" className="h-16 w-16 object-cover rounded border border-amber-600" />}<button disabled={isSubmitting} className="w-full py-3 rounded-xl bg-amber-600 hover:bg-amber-500 disabled:opacity-60 font-bold flex justify-center gap-2 items-center"><Send className="w-4 h-4" />{isSubmitting ? 'Submitting…' : 'Submit Report'}</button></form>}</section>
    <section className="bg-red-950/40 border border-red-800 rounded-2xl p-5 text-center space-y-3"><Radio className="w-7 h-7 text-red-400 mx-auto" /><h2 className="font-bold">Emergency SOS</h2><p className="text-xs text-red-200">For an unreachable or immediately life-threatening situation. This sends an airlift request as a normal emergency incident; it does not dispatch a vehicle directly.</p><div className="flex justify-center gap-2">{[1, 2, 3, 5].map((count) => <button key={count} onClick={() => setSosPersonsCount(count)} className={`px-3 py-1 rounded text-xs font-bold ${sosPersonsCount === count ? 'bg-red-600 text-white' : 'bg-slate-900 text-slate-300'}`}>{count}</button>)}</div><button onClick={handleTriggerSOS} disabled={sosActive} className="px-8 py-3 rounded-xl bg-red-600 hover:bg-red-500 disabled:opacity-60 font-black"><Radio className="w-4 h-4 inline mr-2" />{sosActive ? 'SOS SUBMITTED' : 'EMERGENCY SOS'}</button></section>
  </div>;
};
